steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/trader-frontend/app:latest'
      - '.'

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/trader-frontend/app:latest'

options:
  logging: LEGACY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
